FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y git \
    r-base \
    curl \
    libcurl4-openssl-dev \
    && rm -rf /var/lib/apt/lists/*

COPY libraries /libraries